#############################################################################
####                    G4-DSPS-Detector-Simulation                      ####
#############################################################################
####                                                                     ####
#### Author:                                                             ####
####   Noah Everett (noah.everett@mines.sdsmt.edu)                       ####
####                                                                     ####
#### This file is based on the anniedirt Dockerfile created by me.       ####
#### https://github.com/ANNIEsoft/anniedirt/blob/genie_3_0_6/Dockerfile  ####
####                                                                     ####
#############################################################################
####                                                                     ####
#############################################################################



##############################
########## Set FROM ##########
##############################
FROM noaheverett/physicsbase:1.0.1-x86-Cuda



##############################
########## Set User ##########
##############################
USER root



#############################
########## G4-DSPS ##########
#############################
RUN source /setup_Dockerfile.sh \
 && git clone --recurse-submodules --depth 1 https://github.com/Noah-Everett/DSPS-Detector /DSPS \
 && cd /DSPS \
 && mkdir build \
 && cd build \
 && cmake .. \
 && make -j${NCPU} \
 && cd /DSPS



####################################
########## Pytorch-3dunet ##########
####################################
RUN source /setup_Dockerfile.sh \
 && cd /DSPS/pytorch-3dunet \
 && python setup.py install \
 && cd /


############################
########## Python ##########
############################
RUN source /setup_Dockerfile.sh \
 && pip3 install matplotlib \
                 pandas \
                 scikit-learn \
                 torch \
                 uproot \
                 pyyaml \
                 h5py \
                 tensorboard \
                 scikit-image