/run/initialize
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/gun/particle mu-
#/gun/energy 1800 MeV
/gun/energy 900 MeV
/analysis/setHistoDirName photoSensor_hits_histograms

/analysis/setFileName event_111_2.root
#/gun/position -1.6 -1.6 -1.6 m
/gun/position 0 0 0 m
/gun/direction 1 1 1
/run/beamOn 5

/analysis/setFileName event_-111_2.root
/gun/position 0 0 0 m
/gun/direction -1 -1 -1
/run/beamOn 5