/GDML/save                                                 false
/GDML/fileName                                             geometry.gdml

/output/photoSensor/hits/position/binned/save              true  # true
/output/photoSensor/hits/position/binned/nBinsPerSide      70    # 70
/output/photoSensor/hits/position/absolute/save            false # true
/output/photoSensor/hits/position/relative/save            false # true
/output/photoSensor/hits/position/relative/lens/noSave     *     #   *
#/output/photoSensor/hits/position/relative/lens/save       *     # *
/output/photoSensor/hits/position/initial/save             false # true
/output/photoSensor/hits/momentum/save                     false # true
/output/photoSensor/hits/direction/save                    false # true
/output/photoSensor/hits/direction/relative/save           false # true
/output/photoSensor/hits/direction/relative/lens/noSave    *     #   *
#/output/photoSensor/hits/direction/relative/lens/save      *     # *
/output/photoSensor/hits/time/save                         false # true
/output/photoSensor/hits/process/save                      false # false
/output/photoSensor/hits/photoSensorID/save                false # true
/output/photoSensor/hits/energy/save                       false # false

/output/calorimeter/hits/position/absolute/save            false
/output/calorimeter/hits/position/relative/save            false
/output/calorimeter/hits/position/initial/save             false
/output/calorimeter/hits/momentum/save                     false
/output/calorimeter/hits/direction/save                    false
/output/calorimeter/hits/direction/relative/save           false
/output/calorimeter/hits/time/save                         false
/output/calorimeter/hits/process/save                      false
/output/calorimeter/hits/calorimeterID/save                false
/output/calorimeter/hits/energy/save                       false

/output/lens/hits/position/absolute/save                   false
/output/lens/hits/position/relative/save                   false
/output/lens/hits/position/initial/save                    false
/output/lens/hits/momentum/save                            false
/output/lens/hits/direction/save                           false
/output/lens/hits/direction/relative/save                  false
/output/lens/hits/time/save                                false
/output/lens/hits/process/save                             false
/output/lens/hits/lensID/save                              false
/output/lens/hits/energy/save                              false
/output/lens/hits/transmittance/save                       false

/output/medium/hits/position/absolute/save                 false
/output/medium/hits/position/initial/save                  false
/output/medium/hits/momentum/save                          false
/output/medium/hits/energy/save                            false
/output/medium/hits/process/save                           false
/output/medium/hits/time/save                              false
/output/medium/hits/mediumID/save                          false
/output/medium/hits/process/save                           false
/output/medium/hits/transmittance/save                     false

/output/primary/position/save                              true
/output/primary/momentum/save                              false
/output/primary/emission/photon/save                       false
/output/primary/emission/electron/save                     false
/output/primary/process/save                               false
/output/primary/time/save                                  false
/output/primary/energy/save                                false
/output/primary/volume/save                                false
/output/primary/pdg/save                                   true

/output/photon/length/save                                 false
/output/photon/process/save                                false
/output/photon/time/save                                   false
/output/photon/position/save                               false
/output/photon/momentum/save                               false
/output/photon/energy/save                                 false
/output/photon/volume/save                                 false
/output/photon/stepNumber/save                             false