/geometry/world/size                             2.5 2.5 2.5 m
/geometry/world/material                         G4Air
/geometry/detector/wall/thickness                10 cm
/geometry/detector/wall/material                 G4StainlessSteel
/geometry/detector/medium/material               LXe
/geometry/calorimeter/size                       10.0 2.00 5.00 cm
/geometry/calorimeter/material                   aluminum
/geometry/photoSensor/surface/size               10.0 10.0 0.50 cm
/geometry/photoSensor/surface/material           aluminum
/geometry/photoSensor/body/size                  10.0 10.0 2.00 cm
/geometry/photoSensor/body/material              aluminum
/geometry/lens/parameterFilePath                 /Users/noah-everett/Documents/FNAL/Geant4/USSD_Geant4/build/macros/lensParameters_test.mac
/geometry/directionSensitivePhotoDetector/amount 10 10 10
/geometry/checkOverlaps                          true