/geometry/world/size                             2.5 2.5 2.5 m
/geometry/world/material                         ANNIEWater_unDoped
/geometry/world/visibility                       false
/geometry/world/color                            gray
/geometry/world/alpha                            0
/geometry/world/forceSolid                       true

/geometry/detector/wall/thickness                10 cm
/geometry/detector/wall/material                 ANNIEWater_unDoped #G4StainlessSteel
/geometry/detector/wall/visibility               false
/geometry/detector/wall/color                    black
/geometry/detector/wall/alpha                    0
/geometry/detector/wall/forceSolid               false

/geometry/detector/medium/material               LXe
/geometry/detector/medium/visibility             false
/geometry/detector/medium/color                  cyan
/geometry/detector/medium/alpha                  0
/geometry/detector/medium/forceSolid             false

/geometry/calorimeter/size                       10.0 2.00 40.0 cm
/geometry/calorimeter/material                   aluminum
/geometry/calorimeter/visibility                 true
/geometry/calorimeter/color                      red
/geometry/calorimeter/alpha                      0.3
/geometry/calorimeter/forceSolid                 true

/geometry/photoSensor/surface/size               10.0 10.0 0.50 cm
/geometry/photoSensor/surface/material           ANNIEWater_unDoped
/geometry/photoSensor/surface/visibility         true
/geometry/photoSensor/surface/color              blue
/geometry/photoSensor/surface/alpha              1
/geometry/photoSensor/surface/forceSolid         true

/geometry/photoSensor/body/size                  10.0 10.0 2.00 cm
/geometry/photoSensor/body/material              ANNIEWater_unDoped
/geometry/photoSensor/body/visibility            true
/geometry/photoSensor/body/color                 blue
/geometry/photoSensor/body/alpha                 0.5
/geometry/photoSensor/body/forceSolid            true

/geometry/lens/incramentCurrentLens
/geometry/lens/surfaces/1/radius/x               -50.0 cm
/geometry/lens/surfaces/1/radius/y               45.0 cm
/geometry/lens/surfaces/1/yLimits                10.0 cm
/geometry/lens/surfaces/2/radius/x               100.0 cm
/geometry/lens/surfaces/2/radius/y               45.0 cm
/geometry/lens/surfaces/2/yLimits                10.0 cm
/geometry/lens/distance                          4.0 cm
/geometry/lens/position                          -6 cm
/geometry/lens/material                          SNPH2
/geometry/lens/visibility                        true
/geometry/lens/color                             white
/geometry/lens/alpha                             1
/geometry/lens/forceSolid                        true
/geometry/lens/circular                          false

/geometry/lens/incramentCurrentLens
/geometry/lens/surfaces/1/radius/x               -50.0 cm
/geometry/lens/surfaces/1/radius/y               45.0 cm
/geometry/lens/surfaces/1/yLimits                10.0 cm
/geometry/lens/surfaces/2/radius/x               100.0 cm
/geometry/lens/surfaces/2/radius/y               45.0 cm
/geometry/lens/surfaces/2/yLimits                10.0 cm
/geometry/lens/distance                          4.0 cm
/geometry/lens/position                          -13 cm
/geometry/lens/material                          SNPH2
/geometry/lens/visibility                        true
/geometry/lens/color                             white
/geometry/lens/alpha                             1
/geometry/lens/forceSolid                        true
/geometry/lens/circular                          false

/geometry/directionSensitivePhotoDetector/amount 10 10 10

/geometry/checkOverlaps                          true