/GDML/save                                            false
/GDML/fileName                                        geometry.gdml

/output/photoSensor/hits/position/binned/save         false
/output/photoSensor/hits/position/binned/nBinsPerSide 100
/output/photoSensor/hits/position/absolute/save       true
/output/photoSensor/hits/position/relative/save       false
/output/photoSensor/hits/position/initial/save        true
/output/photoSensor/hits/time/save                    false
/output/photoSensor/hits/process/save                 true
/output/photoSensor/hits/photoSensorID/save           false
/output/photoSensor/hits/energy/save                  false

/output/calorimeter/hits/position/absolute/save       true
/output/calorimeter/hits/position/relative/save       false
/output/calorimeter/hits/position/initial/save        true
/output/calorimeter/hits/time/save                    false
/output/calorimeter/hits/process/save                 true
/output/calorimeter/hits/calorimeterID/save           false
/output/calorimeter/hits/energy/save                  false

/output/lens/hits/position/absolute/save              true
/output/lens/hits/position/relative/save              false
/output/lens/hits/position/initial/save               true
/output/lens/hits/time/save                           false
/output/lens/hits/process/save                        true
/output/lens/hits/lensID/save                         false
/output/lens/hits/energy/save                         false
/output/lens/hits/transmittance/save                  true

/output/medium/hits/position/absolute/save            true
/output/medium/hits/position/initial/save             true
/output/medium/hits/direction/save                    false
/output/medium/hits/energy/save                       false
/output/medium/hits/process/save                      false
/output/medium/hits/time/save                         false
/output/medium/hits/mediumID/save                     false
/output/medium/hits/transmittance/save                true

/output/primary/position/save                         false
/output/primary/direction/save                        false
/output/primary/emission/photon/save                  false
/output/primary/emission/electron/save                false
/output/primary/process/save                          false
/output/primary/time/save                             false
/output/primary/energy/save                           false
/output/primary/volume/save                           false
/output/primary/pdg/save                              false

/output/photon/length/save                            false
/output/photon/process/save                           false
/output/photon/time/save                              false
/output/photon/position/save                          false
/output/photon/direction/save                         false
/output/photon/energy/save                            false
/output/photon/volume/save                            false
/output/photon/stepNumber/save                        true