/GDML/save                                                 false
/GDML/fileName                                             geometry.gdml

/output/photoSensor/hits/position/binned/save              true
/output/photoSensor/hits/position/binned/nBinsPerSide      70
/output/photoSensor/hits/position/absolute/save            true
/output/photoSensor/hits/position/relative/save            true
# /output/photoSensor/hits/position/relative/lens/noSave     *
/output/photoSensor/hits/position/relative/lens/save       *
/output/photoSensor/hits/position/initial/save             true
/output/photoSensor/hits/momentum/save                     true
/output/photoSensor/hits/direction/save                    true
/output/photoSensor/hits/direction/relative/save           true
# /output/photoSensor/hits/direction/relative/lens/noSave    *
/output/photoSensor/hits/direction/relative/lens/save      *
/output/photoSensor/hits/time/save                         true
/output/photoSensor/hits/process/save                      true
/output/photoSensor/hits/photoSensorID/save                true
/output/photoSensor/hits/energy/save                       true

/output/calorimeter/hits/position/absolute/save            true
/output/calorimeter/hits/position/relative/save            true
/output/calorimeter/hits/position/initial/save             true
/output/calorimeter/hits/momentum/save                     true
/output/calorimeter/hits/direction/save                    true
/output/calorimeter/hits/direction/relative/save           true
/output/calorimeter/hits/time/save                         true
/output/calorimeter/hits/process/save                      true
/output/calorimeter/hits/calorimeterID/save                true
/output/calorimeter/hits/energy/save                       true

/output/lens/hits/position/absolute/save                   true
/output/lens/hits/position/relative/save                   true
/output/lens/hits/position/initial/save                    true
/output/lens/hits/momentum/save                            true
/output/lens/hits/direction/save                           true
/output/lens/hits/direction/relative/save                  true
/output/lens/hits/time/save                                true
/output/lens/hits/process/save                             true
/output/lens/hits/lensID/save                              true
/output/lens/hits/energy/save                              true
/output/lens/hits/transmittance/save                       true

/output/medium/hits/position/absolute/save                 true
/output/medium/hits/position/initial/save                  true
/output/medium/hits/momentum/save                          true
/output/medium/hits/energy/save                            true
/output/medium/hits/process/save                           true
/output/medium/hits/time/save                              true
/output/medium/hits/mediumID/save                          true
/output/medium/hits/process/save                           true
/output/medium/hits/transmittance/save                     true

/output/primary/position/save                              true
/output/primary/momentum/save                              true
/output/primary/emission/photon/save                       true
/output/primary/emission/electron/save                     true
/output/primary/process/save                               true
/output/primary/time/save                                  true
/output/primary/energy/save                                true
/output/primary/volume/save                                true
/output/primary/pdg/save                                   true

/output/photon/length/save                                 true
/output/photon/process/save                                true
/output/photon/time/save                                   true
/output/photon/position/save                               true
/output/photon/momentum/save                               true
/output/photon/energy/save                                 true
/output/photon/volume/save                                 true
/output/photon/stepNumber/save                             true